create table IOT.PUBLIC.AUTHORITY
(
  ID   BIGINT not null
    primary key,
  NAME VARCHAR(255)
);

create table IOT.PUBLIC.PROFILE
(
  ID   BIGINT not null
    primary key,
  NAME VARCHAR(255)
);

create table PUBLIC.PROFILE_AUTHORITY
(
  PROFILE_ID   BIGINT not null
    constraint FKPCEPWXVFOYGYTCFET5DRNTVGX
    references PROFILE,
  AUTHORITY_ID BIGINT not null
    constraint FK8DWI49L50QMWM1PT6L2CVBDGT
    references AUTHORITY
);

create table PUBLIC.USER
(
  ID            BIGINT not null
    primary key,
  LASTLOGINTIME TIMESTAMP,
  LOGIN         VARCHAR(255),
  NAME          VARCHAR(255),
  PASSWORD      VARCHAR(255),
  SESSIONID     BIGINT,
  PROFILE_ID    BIGINT
    constraint FKP6S9LGE3H768AJPAPKWF3JEM6
    references PROFILE
);

INSERT INTO PROFILE ("ID", "NAME") VALUES (1, 'admin');
INSERT INTO PROFILE ("ID", "NAME") VALUES (2, 'manager');
INSERT INTO PROFILE ("ID", "NAME") VALUES (3, 'user');

INSERT INTO "PUBLIC"."AUTHORITY" ("ID", "NAME") VALUES (1, 'create page');
INSERT INTO "PUBLIC"."AUTHORITY" ("ID", "NAME") VALUES (2, 'clean story');
INSERT INTO "PUBLIC"."AUTHORITY" ("ID", "NAME") VALUES (3, 'delete users');

INSERT INTO "PUBLIC"."PROFILE_AUTHORITY" ("PROFILE_ID", "AUTHORITY_ID") VALUES (1, 1);
INSERT INTO "PUBLIC"."PROFILE_AUTHORITY" ("PROFILE_ID", "AUTHORITY_ID") VALUES (1, 2);
INSERT INTO "PUBLIC"."PROFILE_AUTHORITY" ("PROFILE_ID", "AUTHORITY_ID") VALUES (1, 3);